title = "Variant Tools"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://vatlab.github.io/vat-docs/content/"
  description = "Documentation for Variant Tools"
  author = "Bo Peng"
  showVisitedLinks = false
  disableInlineCopyToClipBoard = true
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Variant Tools"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://vatlab.github.io/vat-docs/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-twitter'></i> ScriptOfScripts"
url = "https://twitter.com/ScriptOfScripts"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-envelope'></i> bpeng@mdanderson.org"
weight = 13