baseurl = "https://vatlab.github.io/vat-docs/"
languageCode = "en-us"
title = "vatlab"
publishDir = 'docs'

canonifyurls = true
metaDataFormat = "toml"
#theme = "kiss"
theme = "docdock"

copyright = "&copy; <a href=\"https://faculty.mdanderson.org/profiles/bo_peng.html\">Bo Peng, Ph.D. / MD Anderson Cancer Center</a> All rights reserved"
 
googleAnalytics = "UA-107286198-1"

[params]
comments = "http://https://github.com/vatlab/blog/issues"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
enableSocial = true

homeTitle = "vatlab"

[params.opengraph.twitter]
page = "ScriptOfScripts" 

[params.social]

twitter = "ScriptOfScripts"
github = "vatlab"
email = "bpeng@mdanderson.org"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

